name: Docker Runner

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Run Container
        run: docker compose up -d --build
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Display Logs
        run: python3 -m exendlr RCC-Discord-Bot "ready"

      - name: Cleanup Unused Images
        run: docker image prune -f